### ISSUE TITLE
Openseadragon very slow with svs

### ISSUE THREAD

**Issue by nwey** [bayer-science-for-a-better-life/tiffslide#34]
tiffslide is working very,very good with openslide. But Openseadragon is slow. And very slow with svs. Do you got a clue why?

**Comment by ap--** [comment]
Hello @nwey,

could you elaborate a bit on what you mean exactly?

What are you running specifically?
Do you have a code example?

Cheers,
Andreas 😃

**Comment by ap--** [comment]
Hi @nwey 

The script you attached for your webserver backend of your wsi viewer is quite long, so i only had a quick look over it.

What did you try to make it work with tiffslide?

I saw that you make use of the Deepzoom server in openslide. There's no drop-in replacement provided for that in tiffslide. Instead the dzi server in tiffslide is an implementation of a dzi server that serves tiles directly from the wsi file itself instead of requiring to duplicate image data on disk.

I can probably help more, if you provide more details on what you've tried. The code you're running and potentially a minimal example that reproduces the slow reading would be most useful.

Cheers,
Andreas 😃

**Comment by ap--** [comment]
Closing this issue for now.
Feel free to reopen if the issue comes up again!

Cheers
Andreas 😃

**Comment by Chitturi-Teja** [comment]
I have a .svs image to display it in openseadragon in reactjs, I am using flask to covert .svs to .dzi image and it generates .dzi xml file and a folder of jpeg images. I am facing issue integrating these folder of jpeg and .dzi file to openseadragon in reactjs.

**Comment by ap--** [comment]
> I am facing issue integrating these folder of jpeg and .dzi file to openseadragon in reactjs.

Hi @Chitturi-Teja,
it sounds as if you should ask your question in the openseadragon github repository then.

Cheers,
Andreas :smiley:
